### PR TITLE
[CIVIC-1951] Fixed nvm version and SASS declaration.

### PR DESCRIPTION
**Pull request by febdao**
## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Fixed nvm version to `18.14`
2. Fixed SASS declaration error message

**Note:** The SCSS changes are due to an upcoming change to mixed declarations - see https://sass-lang.com/documentation/breaking-changes/mixed-decls/ .

## Screenshots
Screenshot 2024-10-13 at 8 44 04 PM

### CODE REVIEW

**Comment by alan-cole** [comment]
Thanks @febdao - this has a number of fails in linting:

Screenshot 2024-10-15 at 9 28 04 am

Are you able to look up the cause and see if the linter needs to be updated?

**Comment by febdao** [comment]
Hi @alan-cole 
The lint no-duplicate-selectors rule has been disabled, please review it

**Comment by alan-cole** [comment]
Thanks, just to be clear, this will change the output of the content. Here's some example screens of how there's now duplicate selectors.

Screenshot 2024-10-15 at 3 00 29 pm
Screenshot 2024-10-15 at 3 00 11 pm
Screenshot 2024-10-15 at 2 59 44 pm

While I don't think these will cause any problems, I wonder if there's a way to reduce some of these occurrences.

**Review by alan-cole — APPROVED** [review]

**Review by richardgaunt — APPROVED** [review]
Thanks Feb looks good

**Pull request merged**
