### PR TITLE
[#67] Updated checkboxes to the design changes in 1.7.0.

### PR DESCRIPTION
**Pull request by joshua-salsadigital**
Closes https://github.com/civictheme/uikit/issues/67

## Checklist before requesting a review

- [x] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [x] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Updated checkboxes to the design changes in 1.7.0.

### CODE REVIEW

**Comment by joshua-salsadigital** [comment]
@AlexSkrypnyk  Does The checked icon needs update? 
Not able to extract from the figma.

**Comment by AlexSkrypnyk** [comment]
@joshua-salsadigital 
Could you please fully implement the checkbox and test the deployed UI Kit:
- clicking on the label should select the checkbox
- the approach to the checked checkbox look should be using icon-less approach. Please use SVG or other technics to make it bullet-proof.

**Review by AlexSkrypnyk — CHANGES_REQUESTED** [review]
-

**Comment by AlexSkrypnyk** [comment]
closed as the solution direction have changed

**Pull request closed without merging**
